[target.x86_64-unknown-linux-gnu]
# Linker configuration
# Uncomment one of the following blocks if you have the corresponding linker installed.
# Mold is recommended for fastest link times.

# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[build]
# Uncomment to enable sccache for compiler caching
# rustc-wrapper = "sccache"
